// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/gobservability.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *NodeMetrics           `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatsRequest) Reset() {
	*x = NodeStatsRequest{}
	mi := &file_proto_gobservability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatsRequest) ProtoMessage() {}

func (x *NodeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatsRequest.ProtoReflect.Descriptor instead.
func (*NodeStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{0}
}

func (x *NodeStatsRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeStatsRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *NodeStatsRequest) GetMetrics() *NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_gobservability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Flamegraph generation request
type FlamegraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`       // Optional - if empty, generates for entire node
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`                   // Duration in seconds
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`                        // Output format: "svg", "txt", "folded"
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Unique request ID for matching responses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlamegraphRequest) Reset() {
	*x = FlamegraphRequest{}
	mi := &file_proto_gobservability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlamegraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlamegraphRequest) ProtoMessage() {}

func (x *FlamegraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlamegraphRequest.ProtoReflect.Descriptor instead.
func (*FlamegraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{2}
}

func (x *FlamegraphRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *FlamegraphRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *FlamegraphRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *FlamegraphRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FlamegraphRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Flamegraph generation response
type FlamegraphResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FlamegraphData []byte                 `protobuf:"bytes,1,opt,name=flamegraph_data,json=flamegraphData,proto3" json:"flamegraph_data,omitempty"` // Generated flamegraph content
	Format         string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                                       // Actual format returned
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                         // Error message if generation failed
	RequestId      string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                // Request ID to match with request
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlamegraphResponse) Reset() {
	*x = FlamegraphResponse{}
	mi := &file_proto_gobservability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlamegraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlamegraphResponse) ProtoMessage() {}

func (x *FlamegraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlamegraphResponse.ProtoReflect.Descriptor instead.
func (*FlamegraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{3}
}

func (x *FlamegraphResponse) GetFlamegraphData() []byte {
	if x != nil {
		return x.FlamegraphData
	}
	return nil
}

func (x *FlamegraphResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FlamegraphResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FlamegraphResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Metrics struct type based on shared/types/*
type NodeMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CPUStats              `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryStats           `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Network       *NetworkStats          `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Disk          *DiskStats             `protobuf:"bytes,4,opt,name=disk,proto3" json:"disk,omitempty"`
	Pods          []*Pod                 `protobuf:"bytes,5,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_proto_gobservability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{4}
}

func (x *NodeMetrics) GetCpu() *CPUStats {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *NodeMetrics) GetMemory() *MemoryStats {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *NodeMetrics) GetNetwork() *NetworkStats {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *NodeMetrics) GetDisk() *DiskStats {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *NodeMetrics) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

type CPUStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          int64                  `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Nice          int64                  `protobuf:"varint,2,opt,name=nice,proto3" json:"nice,omitempty"`
	System        int64                  `protobuf:"varint,3,opt,name=system,proto3" json:"system,omitempty"`
	Idle          int64                  `protobuf:"varint,4,opt,name=idle,proto3" json:"idle,omitempty"`
	Iowait        int64                  `protobuf:"varint,5,opt,name=iowait,proto3" json:"iowait,omitempty"`
	Irq           int64                  `protobuf:"varint,6,opt,name=irq,proto3" json:"irq,omitempty"`
	Softirq       int64                  `protobuf:"varint,7,opt,name=softirq,proto3" json:"softirq,omitempty"`
	Steal         int64                  `protobuf:"varint,8,opt,name=steal,proto3" json:"steal,omitempty"`
	Total         int64                  `protobuf:"varint,9,opt,name=total,proto3" json:"total,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,10,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUStats) Reset() {
	*x = CPUStats{}
	mi := &file_proto_gobservability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUStats) ProtoMessage() {}

func (x *CPUStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUStats.ProtoReflect.Descriptor instead.
func (*CPUStats) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{5}
}

func (x *CPUStats) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CPUStats) GetNice() int64 {
	if x != nil {
		return x.Nice
	}
	return 0
}

func (x *CPUStats) GetSystem() int64 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *CPUStats) GetIdle() int64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *CPUStats) GetIowait() int64 {
	if x != nil {
		return x.Iowait
	}
	return 0
}

func (x *CPUStats) GetIrq() int64 {
	if x != nil {
		return x.Irq
	}
	return 0
}

func (x *CPUStats) GetSoftirq() int64 {
	if x != nil {
		return x.Softirq
	}
	return 0
}

func (x *CPUStats) GetSteal() int64 {
	if x != nil {
		return x.Steal
	}
	return 0
}

func (x *CPUStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CPUStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

type MemoryStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw values from /proc/meminfo - exactly like types.MemoryStats
	MemTotal     int64 `protobuf:"varint,1,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemFree      int64 `protobuf:"varint,2,opt,name=mem_free,json=memFree,proto3" json:"mem_free,omitempty"`
	MemAvailable int64 `protobuf:"varint,3,opt,name=mem_available,json=memAvailable,proto3" json:"mem_available,omitempty"`
	Buffers      int64 `protobuf:"varint,4,opt,name=buffers,proto3" json:"buffers,omitempty"`
	Cached       int64 `protobuf:"varint,5,opt,name=cached,proto3" json:"cached,omitempty"`
	SwapCached   int64 `protobuf:"varint,6,opt,name=swap_cached,json=swapCached,proto3" json:"swap_cached,omitempty"`
	SwapTotal    int64 `protobuf:"varint,7,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapFree     int64 `protobuf:"varint,8,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	// Calculated values by agent
	MemoryPercent float64 `protobuf:"fixed64,9,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"` // Memory usage percentage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryStats) Reset() {
	*x = MemoryStats{}
	mi := &file_proto_gobservability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStats) ProtoMessage() {}

func (x *MemoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStats.ProtoReflect.Descriptor instead.
func (*MemoryStats) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryStats) GetMemTotal() int64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *MemoryStats) GetMemFree() int64 {
	if x != nil {
		return x.MemFree
	}
	return 0
}

func (x *MemoryStats) GetMemAvailable() int64 {
	if x != nil {
		return x.MemAvailable
	}
	return 0
}

func (x *MemoryStats) GetBuffers() int64 {
	if x != nil {
		return x.Buffers
	}
	return 0
}

func (x *MemoryStats) GetCached() int64 {
	if x != nil {
		return x.Cached
	}
	return 0
}

func (x *MemoryStats) GetSwapCached() int64 {
	if x != nil {
		return x.SwapCached
	}
	return 0
}

func (x *MemoryStats) GetSwapTotal() int64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemoryStats) GetSwapFree() int64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

func (x *MemoryStats) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

type NetworkStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw values from /proc/net/dev - exactly like types.NetworkStats
	BytesReceived      uint64 `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	BytesTransmitted   uint64 `protobuf:"varint,2,opt,name=bytes_transmitted,json=bytesTransmitted,proto3" json:"bytes_transmitted,omitempty"`
	PacketsReceived    uint64 `protobuf:"varint,3,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketsTransmitted uint64 `protobuf:"varint,4,opt,name=packets_transmitted,json=packetsTransmitted,proto3" json:"packets_transmitted,omitempty"`
	ErrorsReceived     uint64 `protobuf:"varint,5,opt,name=errors_received,json=errorsReceived,proto3" json:"errors_received,omitempty"`
	ErrorsTransmitted  uint64 `protobuf:"varint,6,opt,name=errors_transmitted,json=errorsTransmitted,proto3" json:"errors_transmitted,omitempty"`
	// Calculated rates by agent (MB/s)
	RxRate        float64 `protobuf:"fixed64,7,opt,name=rx_rate,json=rxRate,proto3" json:"rx_rate,omitempty"`          // Receive rate in MB/s
	TxRate        float64 `protobuf:"fixed64,8,opt,name=tx_rate,json=txRate,proto3" json:"tx_rate,omitempty"`          // Transmit rate in MB/s
	TotalRate     float64 `protobuf:"fixed64,9,opt,name=total_rate,json=totalRate,proto3" json:"total_rate,omitempty"` // Total rate in MB/s
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_proto_gobservability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkStats) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *NetworkStats) GetBytesTransmitted() uint64 {
	if x != nil {
		return x.BytesTransmitted
	}
	return 0
}

func (x *NetworkStats) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *NetworkStats) GetPacketsTransmitted() uint64 {
	if x != nil {
		return x.PacketsTransmitted
	}
	return 0
}

func (x *NetworkStats) GetErrorsReceived() uint64 {
	if x != nil {
		return x.ErrorsReceived
	}
	return 0
}

func (x *NetworkStats) GetErrorsTransmitted() uint64 {
	if x != nil {
		return x.ErrorsTransmitted
	}
	return 0
}

func (x *NetworkStats) GetRxRate() float64 {
	if x != nil {
		return x.RxRate
	}
	return 0
}

func (x *NetworkStats) GetTxRate() float64 {
	if x != nil {
		return x.TxRate
	}
	return 0
}

func (x *NetworkStats) GetTotalRate() float64 {
	if x != nil {
		return x.TotalRate
	}
	return 0
}

type DiskStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw values from /proc/diskstats - exactly like types.DiskStats
	ReadsCompleted  uint64 `protobuf:"varint,1,opt,name=reads_completed,json=readsCompleted,proto3" json:"reads_completed,omitempty"`
	ReadsMerged     uint64 `protobuf:"varint,2,opt,name=reads_merged,json=readsMerged,proto3" json:"reads_merged,omitempty"`
	SectorsRead     uint64 `protobuf:"varint,3,opt,name=sectors_read,json=sectorsRead,proto3" json:"sectors_read,omitempty"`
	TimeReading     uint64 `protobuf:"varint,4,opt,name=time_reading,json=timeReading,proto3" json:"time_reading,omitempty"`
	WritesCompleted uint64 `protobuf:"varint,5,opt,name=writes_completed,json=writesCompleted,proto3" json:"writes_completed,omitempty"`
	WritesMerged    uint64 `protobuf:"varint,6,opt,name=writes_merged,json=writesMerged,proto3" json:"writes_merged,omitempty"`
	SectorsWritten  uint64 `protobuf:"varint,7,opt,name=sectors_written,json=sectorsWritten,proto3" json:"sectors_written,omitempty"`
	TimeWriting     uint64 `protobuf:"varint,8,opt,name=time_writing,json=timeWriting,proto3" json:"time_writing,omitempty"`
	// Calculated rates by agent (MB/s)
	ReadRate      float64 `protobuf:"fixed64,9,opt,name=read_rate,json=readRate,proto3" json:"read_rate,omitempty"`     // Read rate in MB/s
	WriteRate     float64 `protobuf:"fixed64,10,opt,name=write_rate,json=writeRate,proto3" json:"write_rate,omitempty"` // Write rate in MB/s
	TotalRate     float64 `protobuf:"fixed64,11,opt,name=total_rate,json=totalRate,proto3" json:"total_rate,omitempty"` // Total I/O rate in MB/s
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStats) Reset() {
	*x = DiskStats{}
	mi := &file_proto_gobservability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStats) ProtoMessage() {}

func (x *DiskStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStats.ProtoReflect.Descriptor instead.
func (*DiskStats) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{8}
}

func (x *DiskStats) GetReadsCompleted() uint64 {
	if x != nil {
		return x.ReadsCompleted
	}
	return 0
}

func (x *DiskStats) GetReadsMerged() uint64 {
	if x != nil {
		return x.ReadsMerged
	}
	return 0
}

func (x *DiskStats) GetSectorsRead() uint64 {
	if x != nil {
		return x.SectorsRead
	}
	return 0
}

func (x *DiskStats) GetTimeReading() uint64 {
	if x != nil {
		return x.TimeReading
	}
	return 0
}

func (x *DiskStats) GetWritesCompleted() uint64 {
	if x != nil {
		return x.WritesCompleted
	}
	return 0
}

func (x *DiskStats) GetWritesMerged() uint64 {
	if x != nil {
		return x.WritesMerged
	}
	return 0
}

func (x *DiskStats) GetSectorsWritten() uint64 {
	if x != nil {
		return x.SectorsWritten
	}
	return 0
}

func (x *DiskStats) GetTimeWriting() uint64 {
	if x != nil {
		return x.TimeWriting
	}
	return 0
}

func (x *DiskStats) GetReadRate() float64 {
	if x != nil {
		return x.ReadRate
	}
	return 0
}

func (x *DiskStats) GetWriteRate() float64 {
	if x != nil {
		return x.WriteRate
	}
	return 0
}

func (x *DiskStats) GetTotalRate() float64 {
	if x != nil {
		return x.TotalRate
	}
	return 0
}

type Pod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Pid           int64                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	PodMetrics    *PodMetrics            `protobuf:"bytes,4,opt,name=pod_metrics,json=podMetrics,proto3" json:"pod_metrics,omitempty"`
	PidDetails    *PidDetails            `protobuf:"bytes,5,opt,name=pid_details,json=pidDetails,proto3" json:"pid_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_proto_gobservability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{9}
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Pod) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Pod) GetPodMetrics() *PodMetrics {
	if x != nil {
		return x.PodMetrics
	}
	return nil
}

func (x *Pod) GetPidDetails() *PidDetails {
	if x != nil {
		return x.PidDetails
	}
	return nil
}

type PodMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *PodCPUStats           `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *PodMemoryStats        `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Network       *PodNetworkStats       `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Disk          *PodDiskStats          `protobuf:"bytes,4,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodMetrics) Reset() {
	*x = PodMetrics{}
	mi := &file_proto_gobservability_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodMetrics) ProtoMessage() {}

func (x *PodMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodMetrics.ProtoReflect.Descriptor instead.
func (*PodMetrics) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{10}
}

func (x *PodMetrics) GetCpu() *PodCPUStats {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *PodMetrics) GetMemory() *PodMemoryStats {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *PodMetrics) GetNetwork() *PodNetworkStats {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *PodMetrics) GetDisk() *PodDiskStats {
	if x != nil {
		return x.Disk
	}
	return nil
}

type PodCPUStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Utime         uint64                 `protobuf:"varint,1,opt,name=utime,proto3" json:"utime,omitempty"`                              // User mode jiffies
	Stime         uint64                 `protobuf:"varint,2,opt,name=stime,proto3" json:"stime,omitempty"`                              // Kernel mode jiffies
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"` // Calculated CPU %
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodCPUStats) Reset() {
	*x = PodCPUStats{}
	mi := &file_proto_gobservability_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodCPUStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodCPUStats) ProtoMessage() {}

func (x *PodCPUStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodCPUStats.ProtoReflect.Descriptor instead.
func (*PodCPUStats) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{11}
}

func (x *PodCPUStats) GetUtime() uint64 {
	if x != nil {
		return x.Utime
	}
	return 0
}

func (x *PodCPUStats) GetStime() uint64 {
	if x != nil {
		return x.Stime
	}
	return 0
}

func (x *PodCPUStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

type PodMemoryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmSize        uint64                 `protobuf:"varint,1,opt,name=vm_size,json=vmSize,proto3" json:"vm_size,omitempty"`              // Virtual memory size (KB)
	VmRss         uint64                 `protobuf:"varint,2,opt,name=vm_rss,json=vmRss,proto3" json:"vm_rss,omitempty"`                 // Resident memory size (KB)
	MemPercent    float64                `protobuf:"fixed64,3,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"` // % of total node memory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodMemoryStats) Reset() {
	*x = PodMemoryStats{}
	mi := &file_proto_gobservability_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodMemoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodMemoryStats) ProtoMessage() {}

func (x *PodMemoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodMemoryStats.ProtoReflect.Descriptor instead.
func (*PodMemoryStats) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{12}
}

func (x *PodMemoryStats) GetVmSize() uint64 {
	if x != nil {
		return x.VmSize
	}
	return 0
}

func (x *PodMemoryStats) GetVmRss() uint64 {
	if x != nil {
		return x.VmRss
	}
	return 0
}

func (x *PodMemoryStats) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

type PodNetworkStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BytesReceived    uint64                 `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	BytesTransmitted uint64                 `protobuf:"varint,2,opt,name=bytes_transmitted,json=bytesTransmitted,proto3" json:"bytes_transmitted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PodNetworkStats) Reset() {
	*x = PodNetworkStats{}
	mi := &file_proto_gobservability_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodNetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodNetworkStats) ProtoMessage() {}

func (x *PodNetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodNetworkStats.ProtoReflect.Descriptor instead.
func (*PodNetworkStats) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{13}
}

func (x *PodNetworkStats) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *PodNetworkStats) GetBytesTransmitted() uint64 {
	if x != nil {
		return x.BytesTransmitted
	}
	return 0
}

type PodDiskStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadBytes     uint64                 `protobuf:"varint,1,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`    // Bytes read from disk
	WriteBytes    uint64                 `protobuf:"varint,2,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"` // Bytes written to disk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodDiskStats) Reset() {
	*x = PodDiskStats{}
	mi := &file_proto_gobservability_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodDiskStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodDiskStats) ProtoMessage() {}

func (x *PodDiskStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodDiskStats.ProtoReflect.Descriptor instead.
func (*PodDiskStats) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{14}
}

func (x *PodDiskStats) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *PodDiskStats) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

type PidDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From /proc/{PID}/stat - process basics
	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                  // Filename of executable
	State            string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                                                // Process state
	Priority         int32  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                                         // Priority level
	Nice             int32  `protobuf:"varint,4,opt,name=nice,proto3" json:"nice,omitempty"`                                                 // Nice level
	Threads          int32  `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`                                           // Number of threads
	StartTime        uint64 `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                      // Start time after boot
	RealtimePriority int32  `protobuf:"varint,7,opt,name=realtime_priority,json=realtimePriority,proto3" json:"realtime_priority,omitempty"` // Realtime priority
	Cutime           uint64 `protobuf:"varint,8,opt,name=cutime,proto3" json:"cutime,omitempty"`                                             // Children user time
	Cstime           uint64 `protobuf:"varint,9,opt,name=cstime,proto3" json:"cstime,omitempty"`                                             // Children system time
	TaskCpu          int32  `protobuf:"varint,10,opt,name=task_cpu,json=taskCpu,proto3" json:"task_cpu,omitempty"`                           // Which CPU the task is scheduled on
	// From /proc/{PID}/status - security and scheduling
	Kthread                   int32  `protobuf:"varint,11,opt,name=kthread,proto3" json:"kthread,omitempty"` // Kernel thread flag
	Seccomp                   int32  `protobuf:"varint,12,opt,name=seccomp,proto3" json:"seccomp,omitempty"` // Seccomp mode
	SpeculationIndirectBranch string `protobuf:"bytes,13,opt,name=speculation_indirect_branch,json=speculationIndirectBranch,proto3" json:"speculation_indirect_branch,omitempty"`
	CpusAllowedList           string `protobuf:"bytes,14,opt,name=cpus_allowed_list,json=cpusAllowedList,proto3" json:"cpus_allowed_list,omitempty"`
	MemsAllowedList           string `protobuf:"bytes,15,opt,name=mems_allowed_list,json=memsAllowedList,proto3" json:"mems_allowed_list,omitempty"`
	VoluntaryCtxtSwitches     uint64 `protobuf:"varint,16,opt,name=voluntary_ctxt_switches,json=voluntaryCtxtSwitches,proto3" json:"voluntary_ctxt_switches,omitempty"`
	NonvoluntaryCtxtSwitches  uint64 `protobuf:"varint,17,opt,name=nonvoluntary_ctxt_switches,json=nonvoluntaryCtxtSwitches,proto3" json:"nonvoluntary_ctxt_switches,omitempty"`
	VmPeak                    uint64 `protobuf:"varint,18,opt,name=vm_peak,json=vmPeak,proto3" json:"vm_peak,omitempty"` // Peak virtual memory size (KB)
	VmLck                     uint64 `protobuf:"varint,19,opt,name=vm_lck,json=vmLck,proto3" json:"vm_lck,omitempty"`    // Locked memory size (KB)
	VmPin                     uint64 `protobuf:"varint,20,opt,name=vm_pin,json=vmPin,proto3" json:"vm_pin,omitempty"`    // Pinned memory size (KB)
	// From /proc/{PID}/net - network
	PacketsReceived    uint64 `protobuf:"varint,21,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketsTransmitted uint64 `protobuf:"varint,22,opt,name=packets_transmitted,json=packetsTransmitted,proto3" json:"packets_transmitted,omitempty"`
	ErrorsReceived     uint64 `protobuf:"varint,23,opt,name=errors_received,json=errorsReceived,proto3" json:"errors_received,omitempty"`
	ErrorsTransmitted  uint64 `protobuf:"varint,24,opt,name=errors_transmitted,json=errorsTransmitted,proto3" json:"errors_transmitted,omitempty"`
	// From /proc/{PID}/io
	CancelledWrites uint64 `protobuf:"varint,25,opt,name=cancelled_writes,json=cancelledWrites,proto3" json:"cancelled_writes,omitempty"`
	// Additional process information
	Cmdline       string   `protobuf:"bytes,26,opt,name=cmdline,proto3" json:"cmdline,omitempty"`                 // Command line with arguments
	Stack         []string `protobuf:"bytes,27,rep,name=stack,proto3" json:"stack,omitempty"`                     // Kernel stack trace
	OpenFds       int32    `protobuf:"varint,28,opt,name=open_fds,json=openFds,proto3" json:"open_fds,omitempty"` // Number of open file descriptors
	MaxFds        uint64   `protobuf:"varint,29,opt,name=max_fds,json=maxFds,proto3" json:"max_fds,omitempty"`    // Maximum file descriptors allowed
	Cgroup        []string `protobuf:"bytes,30,rep,name=cgroup,proto3" json:"cgroup,omitempty"`                   // Control groups
	VmData        uint64   `protobuf:"varint,31,opt,name=vm_data,json=vmData,proto3" json:"vm_data,omitempty"`    // Data segment size (KB)
	VmStk         uint64   `protobuf:"varint,32,opt,name=vm_stk,json=vmStk,proto3" json:"vm_stk,omitempty"`       // Stack segment size (KB)
	VmExe         uint64   `protobuf:"varint,33,opt,name=vm_exe,json=vmExe,proto3" json:"vm_exe,omitempty"`       // Text segment size (KB)
	VmLib         uint64   `protobuf:"varint,34,opt,name=vm_lib,json=vmLib,proto3" json:"vm_lib,omitempty"`       // Shared library size (KB)
	VmSwap        uint64   `protobuf:"varint,35,opt,name=vm_swap,json=vmSwap,proto3" json:"vm_swap,omitempty"`    // Swap usage (KB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PidDetails) Reset() {
	*x = PidDetails{}
	mi := &file_proto_gobservability_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PidDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PidDetails) ProtoMessage() {}

func (x *PidDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PidDetails.ProtoReflect.Descriptor instead.
func (*PidDetails) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{15}
}

func (x *PidDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PidDetails) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PidDetails) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PidDetails) GetNice() int32 {
	if x != nil {
		return x.Nice
	}
	return 0
}

func (x *PidDetails) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *PidDetails) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PidDetails) GetRealtimePriority() int32 {
	if x != nil {
		return x.RealtimePriority
	}
	return 0
}

func (x *PidDetails) GetCutime() uint64 {
	if x != nil {
		return x.Cutime
	}
	return 0
}

func (x *PidDetails) GetCstime() uint64 {
	if x != nil {
		return x.Cstime
	}
	return 0
}

func (x *PidDetails) GetTaskCpu() int32 {
	if x != nil {
		return x.TaskCpu
	}
	return 0
}

func (x *PidDetails) GetKthread() int32 {
	if x != nil {
		return x.Kthread
	}
	return 0
}

func (x *PidDetails) GetSeccomp() int32 {
	if x != nil {
		return x.Seccomp
	}
	return 0
}

func (x *PidDetails) GetSpeculationIndirectBranch() string {
	if x != nil {
		return x.SpeculationIndirectBranch
	}
	return ""
}

func (x *PidDetails) GetCpusAllowedList() string {
	if x != nil {
		return x.CpusAllowedList
	}
	return ""
}

func (x *PidDetails) GetMemsAllowedList() string {
	if x != nil {
		return x.MemsAllowedList
	}
	return ""
}

func (x *PidDetails) GetVoluntaryCtxtSwitches() uint64 {
	if x != nil {
		return x.VoluntaryCtxtSwitches
	}
	return 0
}

func (x *PidDetails) GetNonvoluntaryCtxtSwitches() uint64 {
	if x != nil {
		return x.NonvoluntaryCtxtSwitches
	}
	return 0
}

func (x *PidDetails) GetVmPeak() uint64 {
	if x != nil {
		return x.VmPeak
	}
	return 0
}

func (x *PidDetails) GetVmLck() uint64 {
	if x != nil {
		return x.VmLck
	}
	return 0
}

func (x *PidDetails) GetVmPin() uint64 {
	if x != nil {
		return x.VmPin
	}
	return 0
}

func (x *PidDetails) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *PidDetails) GetPacketsTransmitted() uint64 {
	if x != nil {
		return x.PacketsTransmitted
	}
	return 0
}

func (x *PidDetails) GetErrorsReceived() uint64 {
	if x != nil {
		return x.ErrorsReceived
	}
	return 0
}

func (x *PidDetails) GetErrorsTransmitted() uint64 {
	if x != nil {
		return x.ErrorsTransmitted
	}
	return 0
}

func (x *PidDetails) GetCancelledWrites() uint64 {
	if x != nil {
		return x.CancelledWrites
	}
	return 0
}

func (x *PidDetails) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *PidDetails) GetStack() []string {
	if x != nil {
		return x.Stack
	}
	return nil
}

func (x *PidDetails) GetOpenFds() int32 {
	if x != nil {
		return x.OpenFds
	}
	return 0
}

func (x *PidDetails) GetMaxFds() uint64 {
	if x != nil {
		return x.MaxFds
	}
	return 0
}

func (x *PidDetails) GetCgroup() []string {
	if x != nil {
		return x.Cgroup
	}
	return nil
}

func (x *PidDetails) GetVmData() uint64 {
	if x != nil {
		return x.VmData
	}
	return 0
}

func (x *PidDetails) GetVmStk() uint64 {
	if x != nil {
		return x.VmStk
	}
	return 0
}

func (x *PidDetails) GetVmExe() uint64 {
	if x != nil {
		return x.VmExe
	}
	return 0
}

func (x *PidDetails) GetVmLib() uint64 {
	if x != nil {
		return x.VmLib
	}
	return 0
}

func (x *PidDetails) GetVmSwap() uint64 {
	if x != nil {
		return x.VmSwap
	}
	return 0
}

// Bidirectional streaming messages for agent-server communication
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Stats
	//	*AgentMessage_FlamegraphResponse
	Message       isAgentMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_gobservability_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{16}
}

func (x *AgentMessage) GetMessage() isAgentMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetStats() *NodeStatsRequest {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *AgentMessage) GetFlamegraphResponse() *FlamegraphResponse {
	if x != nil {
		if x, ok := x.Message.(*AgentMessage_FlamegraphResponse); ok {
			return x.FlamegraphResponse
		}
	}
	return nil
}

type isAgentMessage_Message interface {
	isAgentMessage_Message()
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Stats struct {
	Stats *NodeStatsRequest `protobuf:"bytes,2,opt,name=stats,proto3,oneof"`
}

type AgentMessage_FlamegraphResponse struct {
	FlamegraphResponse *FlamegraphResponse `protobuf:"bytes,3,opt,name=flamegraph_response,json=flamegraphResponse,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Message() {}

func (*AgentMessage_Stats) isAgentMessage_Message() {}

func (*AgentMessage_FlamegraphResponse) isAgentMessage_Message() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_Ack
	//	*ServerMessage_FlamegraphRequest
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_gobservability_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{17}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetAck() *ServerAck {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerMessage) GetFlamegraphRequest() *FlamegraphRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_FlamegraphRequest); ok {
			return x.FlamegraphRequest
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Ack struct {
	Ack *ServerAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ServerMessage_FlamegraphRequest struct {
	FlamegraphRequest *FlamegraphRequest `protobuf:"bytes,2,opt,name=flamegraph_request,json=flamegraphRequest,proto3,oneof"`
}

func (*ServerMessage_Ack) isServerMessage_Message() {}

func (*ServerMessage_FlamegraphRequest) isServerMessage_Message() {}

type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_proto_gobservability_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{18}
}

func (x *AgentHello) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type ServerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAck) Reset() {
	*x = ServerAck{}
	mi := &file_proto_gobservability_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAck) ProtoMessage() {}

func (x *ServerAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobservability_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAck.ProtoReflect.Descriptor instead.
func (*ServerAck) Descriptor() ([]byte, []int) {
	return file_proto_gobservability_proto_rawDescGZIP(), []int{19}
}

func (x *ServerAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_gobservability_proto protoreflect.FileDescriptor

const file_proto_gobservability_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/gobservability.proto\x12\x0egobservability\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\x10NodeStatsRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\ametrics\x18\x03 \x01(\v2\x1b.gobservability.NodeMetricsR\ametrics\"'\n" +
	"\rStatsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x9e\x01\n" +
	"\x11FlamegraphRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\x8a\x01\n" +
	"\x12FlamegraphResponse\x12'\n" +
	"\x0fflamegraph_data\x18\x01 \x01(\fR\x0eflamegraphData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xfe\x01\n" +
	"\vNodeMetrics\x12*\n" +
	"\x03cpu\x18\x01 \x01(\v2\x18.gobservability.CPUStatsR\x03cpu\x123\n" +
	"\x06memory\x18\x02 \x01(\v2\x1b.gobservability.MemoryStatsR\x06memory\x126\n" +
	"\anetwork\x18\x03 \x01(\v2\x1c.gobservability.NetworkStatsR\anetwork\x12-\n" +
	"\x04disk\x18\x04 \x01(\v2\x19.gobservability.DiskStatsR\x04disk\x12'\n" +
	"\x04pods\x18\x05 \x03(\v2\x13.gobservability.PodR\x04pods\"\xef\x01\n" +
	"\bCPUStats\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x03R\x04user\x12\x12\n" +
	"\x04nice\x18\x02 \x01(\x03R\x04nice\x12\x16\n" +
	"\x06system\x18\x03 \x01(\x03R\x06system\x12\x12\n" +
	"\x04idle\x18\x04 \x01(\x03R\x04idle\x12\x16\n" +
	"\x06iowait\x18\x05 \x01(\x03R\x06iowait\x12\x10\n" +
	"\x03irq\x18\x06 \x01(\x03R\x03irq\x12\x18\n" +
	"\asoftirq\x18\a \x01(\x03R\asoftirq\x12\x14\n" +
	"\x05steal\x18\b \x01(\x03R\x05steal\x12\x14\n" +
	"\x05total\x18\t \x01(\x03R\x05total\x12\x1f\n" +
	"\vcpu_percent\x18\n" +
	" \x01(\x01R\n" +
	"cpuPercent\"\xa0\x02\n" +
	"\vMemoryStats\x12\x1b\n" +
	"\tmem_total\x18\x01 \x01(\x03R\bmemTotal\x12\x19\n" +
	"\bmem_free\x18\x02 \x01(\x03R\amemFree\x12#\n" +
	"\rmem_available\x18\x03 \x01(\x03R\fmemAvailable\x12\x18\n" +
	"\abuffers\x18\x04 \x01(\x03R\abuffers\x12\x16\n" +
	"\x06cached\x18\x05 \x01(\x03R\x06cached\x12\x1f\n" +
	"\vswap_cached\x18\x06 \x01(\x03R\n" +
	"swapCached\x12\x1d\n" +
	"\n" +
	"swap_total\x18\a \x01(\x03R\tswapTotal\x12\x1b\n" +
	"\tswap_free\x18\b \x01(\x03R\bswapFree\x12%\n" +
	"\x0ememory_percent\x18\t \x01(\x01R\rmemoryPercent\"\xe7\x02\n" +
	"\fNetworkStats\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x04R\rbytesReceived\x12+\n" +
	"\x11bytes_transmitted\x18\x02 \x01(\x04R\x10bytesTransmitted\x12)\n" +
	"\x10packets_received\x18\x03 \x01(\x04R\x0fpacketsReceived\x12/\n" +
	"\x13packets_transmitted\x18\x04 \x01(\x04R\x12packetsTransmitted\x12'\n" +
	"\x0ferrors_received\x18\x05 \x01(\x04R\x0eerrorsReceived\x12-\n" +
	"\x12errors_transmitted\x18\x06 \x01(\x04R\x11errorsTransmitted\x12\x17\n" +
	"\arx_rate\x18\a \x01(\x01R\x06rxRate\x12\x17\n" +
	"\atx_rate\x18\b \x01(\x01R\x06txRate\x12\x1d\n" +
	"\n" +
	"total_rate\x18\t \x01(\x01R\ttotalRate\"\x94\x03\n" +
	"\tDiskStats\x12'\n" +
	"\x0freads_completed\x18\x01 \x01(\x04R\x0ereadsCompleted\x12!\n" +
	"\freads_merged\x18\x02 \x01(\x04R\vreadsMerged\x12!\n" +
	"\fsectors_read\x18\x03 \x01(\x04R\vsectorsRead\x12!\n" +
	"\ftime_reading\x18\x04 \x01(\x04R\vtimeReading\x12)\n" +
	"\x10writes_completed\x18\x05 \x01(\x04R\x0fwritesCompleted\x12#\n" +
	"\rwrites_merged\x18\x06 \x01(\x04R\fwritesMerged\x12'\n" +
	"\x0fsectors_written\x18\a \x01(\x04R\x0esectorsWritten\x12!\n" +
	"\ftime_writing\x18\b \x01(\x04R\vtimeWriting\x12\x1b\n" +
	"\tread_rate\x18\t \x01(\x01R\breadRate\x12\x1d\n" +
	"\n" +
	"write_rate\x18\n" +
	" \x01(\x01R\twriteRate\x12\x1d\n" +
	"\n" +
	"total_rate\x18\v \x01(\x01R\ttotalRate\"\xc8\x01\n" +
	"\x03Pod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x03R\x03pid\x12;\n" +
	"\vpod_metrics\x18\x04 \x01(\v2\x1a.gobservability.PodMetricsR\n" +
	"podMetrics\x12;\n" +
	"\vpid_details\x18\x05 \x01(\v2\x1a.gobservability.PidDetailsR\n" +
	"pidDetails\"\xe0\x01\n" +
	"\n" +
	"PodMetrics\x12-\n" +
	"\x03cpu\x18\x01 \x01(\v2\x1b.gobservability.PodCPUStatsR\x03cpu\x126\n" +
	"\x06memory\x18\x02 \x01(\v2\x1e.gobservability.PodMemoryStatsR\x06memory\x129\n" +
	"\anetwork\x18\x03 \x01(\v2\x1f.gobservability.PodNetworkStatsR\anetwork\x120\n" +
	"\x04disk\x18\x04 \x01(\v2\x1c.gobservability.PodDiskStatsR\x04disk\"Z\n" +
	"\vPodCPUStats\x12\x14\n" +
	"\x05utime\x18\x01 \x01(\x04R\x05utime\x12\x14\n" +
	"\x05stime\x18\x02 \x01(\x04R\x05stime\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\"a\n" +
	"\x0ePodMemoryStats\x12\x17\n" +
	"\avm_size\x18\x01 \x01(\x04R\x06vmSize\x12\x15\n" +
	"\x06vm_rss\x18\x02 \x01(\x04R\x05vmRss\x12\x1f\n" +
	"\vmem_percent\x18\x03 \x01(\x01R\n" +
	"memPercent\"e\n" +
	"\x0fPodNetworkStats\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x04R\rbytesReceived\x12+\n" +
	"\x11bytes_transmitted\x18\x02 \x01(\x04R\x10bytesTransmitted\"N\n" +
	"\fPodDiskStats\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x01 \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x02 \x01(\x04R\n" +
	"writeBytes\"\xf2\b\n" +
	"\n" +
	"PidDetails\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04nice\x18\x04 \x01(\x05R\x04nice\x12\x18\n" +
	"\athreads\x18\x05 \x01(\x05R\athreads\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x04R\tstartTime\x12+\n" +
	"\x11realtime_priority\x18\a \x01(\x05R\x10realtimePriority\x12\x16\n" +
	"\x06cutime\x18\b \x01(\x04R\x06cutime\x12\x16\n" +
	"\x06cstime\x18\t \x01(\x04R\x06cstime\x12\x19\n" +
	"\btask_cpu\x18\n" +
	" \x01(\x05R\ataskCpu\x12\x18\n" +
	"\akthread\x18\v \x01(\x05R\akthread\x12\x18\n" +
	"\aseccomp\x18\f \x01(\x05R\aseccomp\x12>\n" +
	"\x1bspeculation_indirect_branch\x18\r \x01(\tR\x19speculationIndirectBranch\x12*\n" +
	"\x11cpus_allowed_list\x18\x0e \x01(\tR\x0fcpusAllowedList\x12*\n" +
	"\x11mems_allowed_list\x18\x0f \x01(\tR\x0fmemsAllowedList\x126\n" +
	"\x17voluntary_ctxt_switches\x18\x10 \x01(\x04R\x15voluntaryCtxtSwitches\x12<\n" +
	"\x1anonvoluntary_ctxt_switches\x18\x11 \x01(\x04R\x18nonvoluntaryCtxtSwitches\x12\x17\n" +
	"\avm_peak\x18\x12 \x01(\x04R\x06vmPeak\x12\x15\n" +
	"\x06vm_lck\x18\x13 \x01(\x04R\x05vmLck\x12\x15\n" +
	"\x06vm_pin\x18\x14 \x01(\x04R\x05vmPin\x12)\n" +
	"\x10packets_received\x18\x15 \x01(\x04R\x0fpacketsReceived\x12/\n" +
	"\x13packets_transmitted\x18\x16 \x01(\x04R\x12packetsTransmitted\x12'\n" +
	"\x0ferrors_received\x18\x17 \x01(\x04R\x0eerrorsReceived\x12-\n" +
	"\x12errors_transmitted\x18\x18 \x01(\x04R\x11errorsTransmitted\x12)\n" +
	"\x10cancelled_writes\x18\x19 \x01(\x04R\x0fcancelledWrites\x12\x18\n" +
	"\acmdline\x18\x1a \x01(\tR\acmdline\x12\x14\n" +
	"\x05stack\x18\x1b \x03(\tR\x05stack\x12\x19\n" +
	"\bopen_fds\x18\x1c \x01(\x05R\aopenFds\x12\x17\n" +
	"\amax_fds\x18\x1d \x01(\x04R\x06maxFds\x12\x16\n" +
	"\x06cgroup\x18\x1e \x03(\tR\x06cgroup\x12\x17\n" +
	"\avm_data\x18\x1f \x01(\x04R\x06vmData\x12\x15\n" +
	"\x06vm_stk\x18  \x01(\x04R\x05vmStk\x12\x15\n" +
	"\x06vm_exe\x18! \x01(\x04R\x05vmExe\x12\x15\n" +
	"\x06vm_lib\x18\" \x01(\x04R\x05vmLib\x12\x17\n" +
	"\avm_swap\x18# \x01(\x04R\x06vmSwap\"\xde\x01\n" +
	"\fAgentMessage\x122\n" +
	"\x05hello\x18\x01 \x01(\v2\x1a.gobservability.AgentHelloH\x00R\x05hello\x128\n" +
	"\x05stats\x18\x02 \x01(\v2 .gobservability.NodeStatsRequestH\x00R\x05stats\x12U\n" +
	"\x13flamegraph_response\x18\x03 \x01(\v2\".gobservability.FlamegraphResponseH\x00R\x12flamegraphResponseB\t\n" +
	"\amessage\"\x9d\x01\n" +
	"\rServerMessage\x12-\n" +
	"\x03ack\x18\x01 \x01(\v2\x19.gobservability.ServerAckH\x00R\x03ack\x12R\n" +
	"\x12flamegraph_request\x18\x02 \x01(\v2!.gobservability.FlamegraphRequestH\x00R\x11flamegraphRequestB\t\n" +
	"\amessage\"N\n" +
	"\n" +
	"AgentHello\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\"%\n" +
	"\tServerAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x88\x02\n" +
	"\vNodeService\x12L\n" +
	"\tSendStats\x12 .gobservability.NodeStatsRequest\x1a\x1d.gobservability.StatsResponse\x12[\n" +
	"\x12GenerateFlamegraph\x12!.gobservability.FlamegraphRequest\x1a\".gobservability.FlamegraphResponse\x12N\n" +
	"\vAgentStream\x12\x1c.gobservability.AgentMessage\x1a\x1d.gobservability.ServerMessage(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_gobservability_proto_rawDescOnce sync.Once
	file_proto_gobservability_proto_rawDescData []byte
)

func file_proto_gobservability_proto_rawDescGZIP() []byte {
	file_proto_gobservability_proto_rawDescOnce.Do(func() {
		file_proto_gobservability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gobservability_proto_rawDesc), len(file_proto_gobservability_proto_rawDesc)))
	})
	return file_proto_gobservability_proto_rawDescData
}

var file_proto_gobservability_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_gobservability_proto_goTypes = []any{
	(*NodeStatsRequest)(nil),      // 0: gobservability.NodeStatsRequest
	(*StatsResponse)(nil),         // 1: gobservability.StatsResponse
	(*FlamegraphRequest)(nil),     // 2: gobservability.FlamegraphRequest
	(*FlamegraphResponse)(nil),    // 3: gobservability.FlamegraphResponse
	(*NodeMetrics)(nil),           // 4: gobservability.NodeMetrics
	(*CPUStats)(nil),              // 5: gobservability.CPUStats
	(*MemoryStats)(nil),           // 6: gobservability.MemoryStats
	(*NetworkStats)(nil),          // 7: gobservability.NetworkStats
	(*DiskStats)(nil),             // 8: gobservability.DiskStats
	(*Pod)(nil),                   // 9: gobservability.Pod
	(*PodMetrics)(nil),            // 10: gobservability.PodMetrics
	(*PodCPUStats)(nil),           // 11: gobservability.PodCPUStats
	(*PodMemoryStats)(nil),        // 12: gobservability.PodMemoryStats
	(*PodNetworkStats)(nil),       // 13: gobservability.PodNetworkStats
	(*PodDiskStats)(nil),          // 14: gobservability.PodDiskStats
	(*PidDetails)(nil),            // 15: gobservability.PidDetails
	(*AgentMessage)(nil),          // 16: gobservability.AgentMessage
	(*ServerMessage)(nil),         // 17: gobservability.ServerMessage
	(*AgentHello)(nil),            // 18: gobservability.AgentHello
	(*ServerAck)(nil),             // 19: gobservability.ServerAck
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_proto_gobservability_proto_depIdxs = []int32{
	20, // 0: gobservability.NodeStatsRequest.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 1: gobservability.NodeStatsRequest.metrics:type_name -> gobservability.NodeMetrics
	5,  // 2: gobservability.NodeMetrics.cpu:type_name -> gobservability.CPUStats
	6,  // 3: gobservability.NodeMetrics.memory:type_name -> gobservability.MemoryStats
	7,  // 4: gobservability.NodeMetrics.network:type_name -> gobservability.NetworkStats
	8,  // 5: gobservability.NodeMetrics.disk:type_name -> gobservability.DiskStats
	9,  // 6: gobservability.NodeMetrics.pods:type_name -> gobservability.Pod
	10, // 7: gobservability.Pod.pod_metrics:type_name -> gobservability.PodMetrics
	15, // 8: gobservability.Pod.pid_details:type_name -> gobservability.PidDetails
	11, // 9: gobservability.PodMetrics.cpu:type_name -> gobservability.PodCPUStats
	12, // 10: gobservability.PodMetrics.memory:type_name -> gobservability.PodMemoryStats
	13, // 11: gobservability.PodMetrics.network:type_name -> gobservability.PodNetworkStats
	14, // 12: gobservability.PodMetrics.disk:type_name -> gobservability.PodDiskStats
	18, // 13: gobservability.AgentMessage.hello:type_name -> gobservability.AgentHello
	0,  // 14: gobservability.AgentMessage.stats:type_name -> gobservability.NodeStatsRequest
	3,  // 15: gobservability.AgentMessage.flamegraph_response:type_name -> gobservability.FlamegraphResponse
	19, // 16: gobservability.ServerMessage.ack:type_name -> gobservability.ServerAck
	2,  // 17: gobservability.ServerMessage.flamegraph_request:type_name -> gobservability.FlamegraphRequest
	0,  // 18: gobservability.NodeService.SendStats:input_type -> gobservability.NodeStatsRequest
	2,  // 19: gobservability.NodeService.GenerateFlamegraph:input_type -> gobservability.FlamegraphRequest
	16, // 20: gobservability.NodeService.AgentStream:input_type -> gobservability.AgentMessage
	1,  // 21: gobservability.NodeService.SendStats:output_type -> gobservability.StatsResponse
	3,  // 22: gobservability.NodeService.GenerateFlamegraph:output_type -> gobservability.FlamegraphResponse
	17, // 23: gobservability.NodeService.AgentStream:output_type -> gobservability.ServerMessage
	21, // [21:24] is the sub-list for method output_type
	18, // [18:21] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_gobservability_proto_init() }
func file_proto_gobservability_proto_init() {
	if File_proto_gobservability_proto != nil {
		return
	}
	file_proto_gobservability_proto_msgTypes[16].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Stats)(nil),
		(*AgentMessage_FlamegraphResponse)(nil),
	}
	file_proto_gobservability_proto_msgTypes[17].OneofWrappers = []any{
		(*ServerMessage_Ack)(nil),
		(*ServerMessage_FlamegraphRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gobservability_proto_rawDesc), len(file_proto_gobservability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gobservability_proto_goTypes,
		DependencyIndexes: file_proto_gobservability_proto_depIdxs,
		MessageInfos:      file_proto_gobservability_proto_msgTypes,
	}.Build()
	File_proto_gobservability_proto = out.File
	file_proto_gobservability_proto_goTypes = nil
	file_proto_gobservability_proto_depIdxs = nil
}
